### ISSUE TITLE
통계청 통계 저작권 안내자료

### ISSUE THREAD

**Issue by YoungjunNa** [statgarten/datatoys#20]
아래를 통해 확인해본 결과 

"공공데이터법 제1조, 제3조에 근거하여 국가통계포털(KOSIS)에서 제공하는 공공데이터는 누구나 이용가능하고, 영리 목적의 이용을 포함한 자유로운 활용이 보장됩니다." 라고 적혀있습니다.

따라서 가이드라인을 준수해, 일부 데이터를 패키지화 해도 문제 없을 것으로 보입니다.

https://kosis.kr/serviceInfo/useGuide.do

**Comment by seungwoolee-222** [comment]
네 확인했습니다.
 #2 Open Data Lists 에 추가하여 코멘트 남기겠습니다.
