### ISSUE TITLE
고용량 데이터 저장소 논의

### ISSUE THREAD

**Issue by YoungjunNa** [statgarten/datatoys#27]
@jinseob2kim @donny-son 

분석 할 때 보다 큰 데이터셋을 제공해보는 것도 좋을 듯 합니다. 
고용량 데이터셋을 내장데이터로 하기에는 github 호스팅 용량 이슈도 있고 패키지 자체가 너무 무거워 지는 것 같아서 의견 주셨던 것처럼 네이버 클라우드나 S3 같은데에서 직접 끌어올 수 있도록 개발해보는 것도 좋을 것 같네요 ㅎㅎ

**Comment by jinseob2kim** [comment]
제가 ncloud에 "statgarten" 이름으로 public bucket 만들었습니다. 창우님 사용법 확인해주시고 공유부탁합니다

**Comment by ChangwooLim** [comment]
https://kr.object.ncloudstorage.com/statgarten/datatoys/data/accident.rda

맨 마지막의 accident.rda를 다른 이름으로 바꾸는 방법을 통해 접근 가능합니다.

**Comment by YoungjunNa** [comment]
@ChangwooLim 님, 저장소에 접근하는 방법을 알 수 있을까요? 제가 업로드할 수 있는 권한 열어주시면 테스트 해보도록 하겠습니다 ㅎㅎ

**Comment by donny-son** [comment]
@ChangwooLim iam 계정 만들어주시면 될 것 같습니다.

**Comment by ChangwooLim** [comment]
@YoungjunNa 영준님, 네이버클라우드 계정 생성하시고 전달 부탁드립니다.

**Comment by YoungjunNa** [comment]
iwantsleep@naver.com 입니다!

**Comment by ChangwooLim** [comment]
<img width="485" alt="스크린샷 2023-05-23 오후 1 51 19" src="https://github.com/statgarten/datatoys/assets/86377226/abf554a6-aad4-4a72-a11b-ea8b99d9204d">
object storage 신청해야 사용 가능하다고 합니다.

**Comment by YoungjunNa** [comment]
이용신청 완료하였습니다.

**Comment by ChangwooLim** [comment]
추가했습니다. 확인부탁드려요

**Comment by YoungjunNa** [comment]
https://data.seoul.go.kr/etc/aiEduData.do

서울시에서 제공하는 학습용 데이터들을 제공하는 것도 좋을 것 같습니다 ㅎㅎ
