### ISSUE TITLE
일부 데이터 description이 반영 이슈

### ISSUE THREAD

**Issue by YoungjunNa** [statgarten/datatoys#39]
최근 업로드된 일부 데이터 description이 반영이 안되는 것 같은데 이유가 뭘까요..?
data.R 파일을 살펴봐도 문제가 없어 보이는데.. 음...

<img width="431" alt="스크린샷 2023-08-23 오전 10 42 49" src="https://github.com/statgarten/datatoys/assets/28377612/24a53727-3613-4b5c-9400-ad24e4d5e7b6">

```
library(datatoys)
library(dplyr)

data(package = "datatoys")$results %>%
  as_tibble() %>%
  select(Item, Title) %>%
  rename("데이터셋" = "Item") %>%
  tidyr::separate(Title, c("출처", "설명"), sep = " ", extra = "merge") %>%
  arrange(출처) %>% View()
```

**Comment by seungwoolee-222** [comment]
data.R 파일 봤는데 이전과 동일하게 작성했는데 왜 그런지 모르겠습니다. 
다시 한번 확인해보도록 하겠습니다.

**Comment by seungwoolee-222** [comment]
#10 을 통해 작성 후 확인해본 결과, 오늘까지 업로드한 데이터까지 총 80개 description 반영되는 것으로 확인됩니다!

**Comment by YoungjunNa** [comment]
아주 좋습니다 !
